events { worker_connections 1024; }

http {
    upstream gateway  { server mall-gateway:8080; }
    upstream admin_ui { server admin-web:3000; }

    # 压缩
    gzip on;
    gzip_types text/plain application/json application/javascript text/css;

    server {
        listen 80;
        server_name _;

        # 管理后台
        location / {
            proxy_pass http://admin_ui;
            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        }

        # API 网关
        location /api/ {
            proxy_pass http://gateway;
            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_read_timeout 60s;
        }
    }
}
